/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three"
import React, { useEffect, useRef } from "react"
import { useGLTF, useAnimations, PerspectiveCamera } from "@react-three/drei"
import { useFrame } from "@react-three/fiber"



export default function Model({ scroll, ...props }) { 
  
  //const t = useRef(0)
  const group = useRef()
  const { nodes, materials, animations } = useGLTF("skeleton-test.glb")
  const { actions/*, mixer*/ } = useAnimations(animations, group)
  //const extras = { receiveShadow: true, castShadow: true, "material-envMapIntensity": 0.2 }
  
  //useEffect(() => void (console.log(actions), actions.rigAction.play().paused = true), [])
  useEffect(() => (actions["CameraAction.001"].play().paused = true))

  useFrame(() => {
   // actions.rigAction.time = THREE.MathUtils.lerp(actions.rigAction.time, actions.rigAction.getClip().duration * scroll.current, 0.05)
   actions["CameraAction.001"].time = THREE.MathUtils.lerp(actions["CameraAction.001"].time, actions["CameraAction.001"].getClip().duration * scroll.current, 0.05)
  }, [])

  
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Camera" position={[0.59, 1.13, 4.02]} rotation={[1.51, 0.01, -0.13]}>
        <PerspectiveCamera makeDefault far={1000} near={0.1} fov={39.6} rotation={[-Math.PI / 2, 0, 0]} />
      </group>
      <group position={[0, -1.03, 0]}>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <group position={[0, 0.06, 1.01]} rotation={[1.82, 0, 0]}>
            <group position={[0, 0.15, 0]} rotation={[0.1, 0, 0]}>
              <group position={[0, 0.06, 0]} rotation={[-0.28, 0, 0]}>
                <group position={[0, 0.06, 0]} rotation={[-0.26, 0, 0]}>
                  <group position={[0, 0.1, 0]} rotation={[-0.06, 0, 0]}>
                    <group position={[0, 0.09, 0]} rotation={[0.13, 0, 0]}>
                      <group position={[0, 0.1, 0]} rotation={[0.25, 0, 0]}>
                        <group position={[0, 0.1, 0]} rotation={[0.1, 0, 0]}>
                          <group position={[0, 0.06, 0]} rotation={[-0.04, 0, 0]} />
                        </group>
                      </group>
                    </group>
                  </group>
                </group>
              </group>
            </group>
          </group>
          <group position={[0, 0.04, 1.08]}>
            <group position={[0, -0.04, 0.13]}>
              <group rotation={[1.64, 0, 0]} />
              <group position={[0, 0, 0.06]}>
                <group position={[0, 0.02, 0.09]}>
                  <group rotation={[1.58, 0, 0]}>
                    <group position={[0, 0.09, -0.02]} />
                    <group position={[0, 0.18, -0.04]} />
                    <group position={[0, 0.29, -0.02]} />
                    <group position={[0, 0.34, -0.01]} />
                    <group position={[0, 0.41, 0]} rotation={[-1.58, 0, 0]}>
                      <group rotation={[Math.PI / 2, 0, 0]}>
                        <group position={[0, 0, 0.03]}>
                          <group position={[0.05, 0.11, 0.1]} rotation={[-Math.PI / 2, 0, -Math.PI]} />
                          <group position={[0.05, 0.11, 0.1]} rotation={[-1.73, -0.31, 2.21]} />
                          <group position={[0.05, 0.11, 0.1]} rotation={[-2.27, -1.03, 2]} />
                          <group position={[0.05, 0.11, 0.1]} rotation={[2.16, 0.61, -0.19]} />
                          <group position={[0.05, 0.11, 0.1]} rotation={[-1.82, 0.45, -2.13]} />
                          <group position={[0.05, 0.11, 0.1]} rotation={[-1.55, -0.02, -1.61]} />
                          <group position={[0.05, 0.11, 0.1]} rotation={[-1.29, -0.52, -2.17]} />
                          <group position={[0.05, 0.11, 0.1]} rotation={[1.09, -0.76, -0.19]} />
                          <group position={[0.05, 0.11, 0.1]} rotation={[-1.27, 0.87, 2.51]} />
                          <group position={[-0.05, 0.11, 0.1]} rotation={[-Math.PI / 2, 0, -Math.PI]} />
                          <group position={[-0.05, 0.11, 0.1]} rotation={[-1.73, 0.31, -2.21]} />
                          <group position={[-0.05, 0.11, 0.1]} rotation={[-2.27, 1.03, -2]} />
                          <group position={[-0.05, 0.11, 0.1]} rotation={[2.16, -0.61, 0.19]} />
                          <group position={[-0.05, 0.11, 0.1]} rotation={[-1.82, -0.45, 2.13]} />
                          <group position={[-0.05, 0.11, 0.1]} rotation={[-1.55, 0.02, 1.61]} />
                          <group position={[-0.05, 0.11, 0.1]} rotation={[-1.29, 0.52, 2.17]} />
                          <group position={[-0.05, 0.11, 0.1]} rotation={[1.09, 0.76, 0.19]} />
                          <group position={[-0.05, 0.11, 0.1]} rotation={[-1.27, -0.87, -2.51]} />
                          <group position={[0, 0.02, 0]} rotation={[2, -0.01, 0.02]}>
                            <group position={[0, 0.08, -0.04]} rotation={[-0.21, 0.01, -0.02]} />
                            <group position={[0, 0.08, -0.04]} rotation={[-0.21, 0.01, -0.02]} />
                          </group>
                          <group position={[0, 0.02, 0]} rotation={[2, -0.01, 0.02]} />
                          <group position={[0, 0.04, 0.01]} rotation={[2.14, 0, 0.01]} />
                          <group position={[0, 0.07, 0.02]} rotation={[2.36, 0, 0.01]} />
                          <group position={[0, 0.08, 0.03]} rotation={[2.5, 0, 0]} />
                          <group position={[0, 0.09, 0.04]} rotation={[2.54, 0, 0]} />
                        </group>
                      </group>
                    </group>
                    <group rotation={[-0.26, 0, 0]}>
                      <group position={[0, 0.09, 0]} rotation={[0.13, 0, 0]}>
                        <group position={[0, 0.1, 0]} rotation={[0.25, 0, 0]}>
                          <group position={[0.02, 0.08, 0.07]} rotation={[-1.74, 0.09, -1.22]}>
                            <group position={[0, 0.19, -0.03]} rotation={[2.06, 1.1, 2.86]}>
                              <group position={[0, 0.15, 0]} />
                              <group position={[0, 0.31, 0]} rotation={[0.53, 0, 0]}>
                                <group position={[0, 0.14, 0]} rotation={[0, -0.01, 0]} />
                                <group position={[0, 0.28, 0]} rotation={[-0.35, 0, -0.07]}>
                                  <group rotation={[0.35, 0.03, 0.07]} />
                                </group>
                              </group>
                            </group>
                            <group position={[0, 0.19, -0.03]} rotation={[0.09, 0, 1.23]}>
                              <group rotation={[1.74, -0.09, -3.05]} />
                              <group rotation={[1.74, -0.09, -3.05]}>
                                <group position={[0, 0.31, 0]} rotation={[0.53, 0, 0]}>
                                  <group position={[0, 0.28, 0]} rotation={[-0.35, 0, -0.07]} />
                                </group>
                              </group>
                              <group rotation={[1.74, -0.09, -3.05]} />
                            </group>
                            <group position={[0, 0.19, -0.03]} rotation={[2.06, 1.1, 2.86]}>
                              <group position={[0, 0.15, 0]}>
                                <group position={[0, 0.15, 0]} rotation={[0.53, 0, 0]}>
                                  <group position={[0, 0.14, 0]} rotation={[0, -0.01, 0]}>
                                    <group position={[0, 0.14, 0]} rotation={[-0.35, 0.01, -0.07]}>
                                      <group position={[-0.01, 0.04, 0.02]} rotation={[-2.85, 1.41, 3.01]}>
                                        <group position={[0, 0.07, 0]} rotation={[0.3, -0.08, 0.13]}>
                                          <group position={[0, 0.05, 0]} rotation={[0.28, -0.05, 0.13]}>
                                            <group position={[0, 0.03, 0]} rotation={[0.41, -0.42, 0.05]} />
                                          </group>
                                        </group>
                                        <group position={[0, 0.07, 0]} rotation={[0.3, -0.08, 0.13]}>
                                          <group position={[0, 0.05, 0]} rotation={[0.28, -0.05, 0.13]} />
                                        </group>
                                        <group position={[-0.02, -0.01, 0]} rotation={[-1.98, 0.96, 2.32]}>
                                          <group position={[0, 0.05, 0]} rotation={[0.18, -0.3, 0.44]}>
                                            <group position={[0, 0.04, 0]} rotation={[0.65, -0.36, 0.41]} />
                                          </group>
                                        </group>
                                        <group position={[-0.02, -0.01, 0]} rotation={[-1.98, 0.96, 2.32]}>
                                          <group position={[0, 0.05, 0]} rotation={[0.18, -0.3, 0.44]} />
                                        </group>
                                      </group>
                                      <group position={[-0.01, 0.04, 0]} rotation={[-2.75, 1.52, 2.84]}>
                                        <group position={[0, 0.08, 0]} rotation={[0.35, -0.01, 0.17]}>
                                          <group position={[0, 0.05, 0]} rotation={[0.34, -0.14, 0.07]}>
                                            <group position={[0, 0.04, 0]} rotation={[0.48, -0.14, 0.15]} />
                                          </group>
                                        </group>
                                        <group position={[0, 0.08, 0]} rotation={[0.35, -0.01, 0.17]}>
                                          <group position={[0, 0.05, 0]} rotation={[0.34, -0.14, 0.07]} />
                                        </group>
                                      </group>
                                      <group position={[0, 0.04, -0.02]} rotation={[-0.07, 1.45, 0.03]}>
                                        <group position={[0, 0.07, 0]} rotation={[0.38, 0.02, 0.12]}>
                                          <group position={[0, 0.05, 0]} rotation={[0.38, -0.07, 0.02]}>
                                            <group position={[0, 0.04, 0]} rotation={[0.38, -0.14, 0.1]} />
                                          </group>
                                        </group>
                                        <group position={[0, 0.07, 0]} rotation={[0.38, 0.02, 0.12]}>
                                          <group position={[0, 0.05, 0]} rotation={[0.38, -0.07, 0.02]} />
                                        </group>
                                      </group>
                                      <group position={[0, 0.04, -0.03]} rotation={[0.13, 1.35, -0.33]}>
                                        <group position={[0, 0.07, 0]} rotation={[0.38, -0.05, 0.25]}>
                                          <group position={[0, 0.05, 0]} rotation={[0.2, -0.05, 0]}>
                                            <group position={[0, 0.02, 0]} rotation={[0.09, 0.53, 0.03]} />
                                          </group>
                                        </group>
                                        <group position={[0, 0.07, 0]} rotation={[0.38, -0.05, 0.25]}>
                                          <group position={[0, 0.05, 0]} rotation={[0.2, -0.05, 0]} />
                                        </group>
                                      </group>
                                    </group>
                                  </group>
                                </group>
                              </group>
                            </group>
                          </group>
                          <group position={[-0.02, 0.08, 0.07]} rotation={[-1.74, -0.09, 1.22]}>
                            <group position={[0, 0.19, -0.03]} rotation={[2.06, -1.1, -2.86]}>
                              <group position={[0, 0.15, 0]} />
                              <group position={[0, 0.31, 0]} rotation={[0.53, 0, 0]}>
                                <group position={[0, 0.14, 0]} rotation={[0, 0.01, 0]} />
                                <group position={[0, 0.28, 0]} rotation={[-0.35, 0, 0.07]}>
                                  <group rotation={[0.35, -0.03, -0.07]} />
                                </group>
                              </group>
                            </group>
                            <group position={[0, 0.19, -0.03]} rotation={[0.09, 0, -1.23]}>
                              <group rotation={[1.74, 0.09, 3.05]} />
                              <group rotation={[1.74, 0.09, 3.05]}>
                                <group position={[0, 0.31, 0]} rotation={[0.53, 0, 0]}>
                                  <group position={[0, 0.28, 0]} rotation={[-0.35, 0, 0.07]} />
                                </group>
                              </group>
                              <group rotation={[1.74, 0.09, 3.05]} />
                            </group>
                            <group position={[0, 0.19, -0.03]} rotation={[2.06, -1.1, -2.86]}>
                              <group position={[0, 0.15, 0]}>
                                <group position={[0, 0.15, 0]} rotation={[0.53, 0, 0]}>
                                  <group position={[0, 0.14, 0]} rotation={[0, 0.01, 0]}>
                                    <group position={[0, 0.14, 0]} rotation={[-0.35, -0.01, 0.07]}>
                                      <group position={[0.01, 0.04, 0.02]} rotation={[-2.85, -1.41, -3.01]}>
                                        <group position={[0, 0.07, 0]} rotation={[0.3, 0.08, -0.13]}>
                                          <group position={[0, 0.05, 0]} rotation={[0.28, 0.05, -0.13]}>
                                            <group position={[0, 0.03, 0]} rotation={[0.41, 0.42, -0.05]} />
                                          </group>
                                        </group>
                                        <group position={[0, 0.07, 0]} rotation={[0.3, 0.08, -0.13]}>
                                          <group position={[0, 0.05, 0]} rotation={[0.28, 0.05, -0.13]} />
                                        </group>
                                        <group position={[0.02, -0.01, 0]} rotation={[-1.98, -0.96, -2.32]}>
                                          <group position={[0, 0.05, 0]} rotation={[0.18, 0.3, -0.44]}>
                                            <group position={[0, 0.04, 0]} rotation={[0.65, 0.36, -0.41]} />
                                          </group>
                                        </group>
                                        <group position={[0.02, -0.01, 0]} rotation={[-1.98, -0.96, -2.32]}>
                                          <group position={[0, 0.05, 0]} rotation={[0.18, 0.3, -0.44]} />
                                        </group>
                                      </group>
                                      <group position={[0.01, 0.04, 0]} rotation={[-2.75, -1.52, -2.84]}>
                                        <group position={[0, 0.08, 0]} rotation={[0.35, 0.01, -0.17]}>
                                          <group position={[0, 0.05, 0]} rotation={[0.34, 0.14, -0.07]}>
                                            <group position={[0, 0.04, 0]} rotation={[0.48, 0.14, -0.15]} />
                                          </group>
                                        </group>
                                        <group position={[0, 0.08, 0]} rotation={[0.35, 0.01, -0.17]}>
                                          <group position={[0, 0.05, 0]} rotation={[0.34, 0.14, -0.07]} />
                                        </group>
                                      </group>
                                      <group position={[0, 0.04, -0.02]} rotation={[-0.07, -1.45, -0.03]}>
                                        <group position={[0, 0.07, 0]} rotation={[0.38, -0.02, -0.12]}>
                                          <group position={[0, 0.05, 0]} rotation={[0.38, 0.07, -0.02]}>
                                            <group position={[0, 0.04, 0]} rotation={[0.38, 0.14, -0.1]} />
                                          </group>
                                        </group>
                                        <group position={[0, 0.07, 0]} rotation={[0.38, -0.02, -0.12]}>
                                          <group position={[0, 0.05, 0]} rotation={[0.38, 0.07, -0.02]} />
                                        </group>
                                      </group>
                                      <group position={[0, 0.04, -0.03]} rotation={[0.13, -1.35, 0.33]}>
                                        <group position={[0, 0.07, 0]} rotation={[0.38, 0.05, -0.25]}>
                                          <group position={[0, 0.05, 0]} rotation={[0.2, 0.05, 0]}>
                                            <group position={[0, 0.02, 0]} rotation={[0.09, -0.53, -0.03]} />
                                          </group>
                                        </group>
                                        <group position={[0, 0.07, 0]} rotation={[0.38, 0.05, -0.25]}>
                                          <group position={[0, 0.05, 0]} rotation={[0.2, 0.05, 0]} />
                                        </group>
                                      </group>
                                    </group>
                                  </group>
                                </group>
                              </group>
                            </group>
                          </group>
                          <group position={[0.11, -0.08, 0.01]} rotation={[-1.7, 0, -Math.PI]} />
                          <group position={[-0.11, -0.08, 0.01]} rotation={[-1.7, 0, -Math.PI]} />
                          <group position={[0, 0.1, 0]} rotation={[0.1, 0, 0]} />
                        </group>
                      </group>
                    </group>
                  </group>
                </group>
                <group rotation={[1.38, 0, 0]} />
              </group>
            </group>
            <group position={[0, -0.04, 0.13]}>
              <group position={[0, 0.02, -0.06]}>
                <group position={[0, 0.04, -0.15]} rotation={[1.82, 0, 0]}>
                  <group rotation={[-1.95, -0.74, -2.21]} />
                  <group rotation={[-1.95, 0.74, 2.21]} />
                  <group position={[0.1, 0.04, 0.09]} rotation={[2.91, -0.04, 0.02]}>
                    <group position={[0, 0.24, 0]} />
                    <group position={[0, 0.49, 0]} rotation={[0.08, 0, 0]}>
                      <group position={[0, 0.23, 0]} rotation={[0, 0.02, 0]} />
                      <group position={[0, 0.46, 0]} rotation={[-1.13, 0.04, 0.03]}>
                        <group rotation={[1.12, 0.58, -0.01]} />
                        <group position={[0, 0.14, 0]} rotation={[2.59, 0, 3.14]} />
                      </group>
                    </group>
                  </group>
                  <group position={[-0.11, 0.04, 0.09]} rotation={[2.91, 0, -0.02]}>
                    <group position={[0, 0.24, 0]} />
                    <group position={[0, 0.49, 0]} rotation={[0.09, 0, 0]}>
                      <group position={[0, 0.23, 0]} />
                      <group position={[0, 0.46, 0]} rotation={[-1.13, -0.02, 0.01]}>
                        <group rotation={[1.12, -0.63, 0.01]} />
                        <group position={[0, 0.14, 0]} rotation={[2.59, 0, -3.14]} />
                      </group>
                    </group>
                  </group>
                  <group position={[0.1, 0.04, 0.09]} rotation={[-1.82, 0, 0]}>
                    <group rotation={[-1.55, -0.04, 0.02]} />
                    <group rotation={[-1.57, 0.58, 0.05]}>
                      <group position={[0, 0.49, 0]} rotation={[0.09, 0, 0]}>
                        <group position={[0, 0.46, 0]} rotation={[-1.19, -0.25, -0.53]} />
                      </group>
                    </group>
                    <group rotation={[-1.55, -0.04, 0.02]} />
                  </group>
                  <group position={[0.1, 0.04, 0.09]} rotation={[2.91, -0.04, 0.02]}>
                    <group position={[0, 0.24, 0]}>
                      <group position={[0, 0.24, 0]} rotation={[0.08, 0, 0]}>
                        <group position={[0, 0.23, 0]} rotation={[0, 0.02, 0]}>
                          <group position={[0, 0.23, 0]} rotation={[-1.12, 0.02, 0.01]} />
                        </group>
                      </group>
                    </group>
                  </group>
                  <group position={[-0.11, 0.04, 0.09]} rotation={[-1.82, 0, 0]}>
                    <group rotation={[-1.55, 0, -0.02]} />
                    <group rotation={[-1.58, -0.63, -0.06]}>
                      <group position={[0, 0.49, 0]} rotation={[0.09, 0, 0]}>
                        <group position={[0, 0.46, 0]} rotation={[-1.2, 0.27, 0.58]} />
                      </group>
                    </group>
                    <group rotation={[-1.55, 0, -0.02]} />
                  </group>
                  <group position={[-0.11, 0.04, 0.09]} rotation={[2.91, 0, -0.02]}>
                    <group position={[0, 0.24, 0]}>
                      <group position={[0, 0.24, 0]} rotation={[0.09, 0, 0]}>
                        <group position={[0, 0.23, 0]}>
                          <group position={[0, 0.23, 0]} rotation={[-1.13, -0.01, 0.01]} />
                        </group>
                      </group>
                    </group>
                  </group>
                </group>
                <group rotation={[1.92, 0, 0]} />
              </group>
            </group>
          </group>
        </group>
        <group position={[-0.23, 1.02, 0.02]} rotation={[0, 0.11, -3.14]} />
        <group position={[-0.23, 1.02, 0.02]} rotation={[0, 0.11, -3.14]} />
        <group position={[0.23, 1.02, 0.02]} rotation={[0, -0.11, 3.14]} />
        <group position={[0.23, 1.02, 0.02]} rotation={[0, -0.11, 3.14]} />
        <group position={[-0.09, 0.09, -0.02]} rotation={[2.12, 0, 0]} />
        <group position={[-0.09, 0.09, -0.02]} rotation={[2.12, 0, 0]}>
          <group position={[0, 0.14, 0]} rotation={[2.59, 0, 0]}>
            <group position={[0.04, 0.15, -0.01]}>
              <group position={[-0.08, 0, 0]}>
                <group position={[0.04, 0, 0]} rotation={[0, 0, Math.PI]} />
              </group>
            </group>
            <group position={[0, 0.12, 0.07]} />
          </group>
        </group>
        <group position={[0.09, 0.09, -0.02]} rotation={[2.12, 0, 0]} />
        <group position={[0.09, 0.09, -0.02]} rotation={[2.12, 0, 0]}>
          <group position={[0, 0.14, 0]} rotation={[2.59, 0, 0]}>
            <group position={[-0.04, 0.15, -0.01]}>
              <group position={[0.08, 0, 0]}>
                <group position={[-0.04, 0, 0]} rotation={[0, 0, -Math.PI]} />
              </group>
            </group>
            <group position={[0, 0.12, 0.07]} />
          </group>
        </group>
        <mesh geometry={nodes.Skeleton.geometry} material={materials.Skeleton} />
      </group>
      <group position={[0, 1.01, -0.06]} rotation={[0.25, 0, 0]}>
        <group position={[0, 0.15, 0]} rotation={[0.1, 0, 0]}>
          <group position={[0, 0.06, 0]} rotation={[-0.28, 0, 0]}>
            <group position={[0, 0.06, 0]} rotation={[-0.26, 0, 0]}>
              <group position={[0, 0.1, 0]} rotation={[-0.06, 0, 0]}>
                <group position={[0, 0.09, 0]} rotation={[0.13, 0, 0]}>
                  <group position={[0, 0.1, 0]} rotation={[0.25, 0, 0]}>
                    <group position={[0, 0.1, 0]} rotation={[0.1, 0, 0]}>
                      <group position={[0, 0.06, 0]} rotation={[-0.04, 0, 0]}>
                        <group position={[0, 0.06, 0]} rotation={[-0.19, 0, 0]}>
                          <group position={[0, 0, 0.03]}>
                            <group position={[0, 0.12, 0.13]} rotation={[2.49, 0, 0]}>
                              <group position={[0, 0.05, 0]} rotation={[-0.1, 0, 0]}>
                                <group position={[0, 0.02, 0]} rotation={[1.92, 0, 0]}>
                                  <group position={[0, 0.01, 0]} rotation={[0.35, 0, 0]} />
                                </group>
                              </group>
                            </group>
                            <group position={[0, 0.03, 0.15]} rotation={[-1.54, -0.02, -1.3]} />
                            <group position={[0, 0.02, 0.14]} rotation={[-1.4, -0.19, -1.13]} />
                            <group position={[0, -0.04, 0.07]} rotation={[1.65, 0, 0]}>
                              <group position={[0, 0.06, 0]} rotation={[-1.29, 0, 0]} />
                            </group>
                            <group position={[0.09, 0.08, 0.01]} rotation={[0.03, -0.22, -0.18]}>
                              <group position={[0, 0.04, 0]} rotation={[-1.38, -0.15, -0.45]}>
                                <group position={[0, 0.03, 0]} rotation={[-1.89, -0.68, -0.21]}>
                                  <group position={[0, 0.04, 0]} rotation={[-0.29, -0.62, 0.64]} />
                                </group>
                              </group>
                            </group>
                            <group position={[-0.09, 0.08, 0.01]} rotation={[0.03, 0.22, 0.18]}>
                              <group position={[0, 0.04, 0]} rotation={[-1.38, 0.15, 0.45]}>
                                <group position={[0, 0.03, 0]} rotation={[-1.89, 0.68, 0.21]}>
                                  <group position={[0, 0.04, 0]} rotation={[-0.29, 0.62, -0.64]} />
                                </group>
                              </group>
                            </group>
                            <group position={[0, 0.03, 0.15]} rotation={[-1.54, 0.02, 1.3]} />
                            <group position={[0, 0.02, 0.14]} rotation={[-1.4, 0.19, 1.13]} />
                            <group position={[0.08, 0.12, 0.1]} rotation={[-0.95, 0.91, 1.96]}>
                              <group position={[0, 0.02, 0]} rotation={[-0.48, 0.74, 0.04]}>
                                <group position={[0, 0.01, 0]} rotation={[-0.09, 0.4, -0.6]} />
                              </group>
                            </group>
                            <group position={[0.08, 0.11, 0.1]} rotation={[-0.85, 0.96, 2]}>
                              <group position={[0, 0.02, 0]} rotation={[-0.28, 0.88, -0.18]}>
                                <group position={[0, 0.02, 0]} rotation={[-0.32, 0.42, -0.59]}>
                                  <group position={[0, 0.01, 0]} rotation={[-0.24, 0.56, -0.03]}>
                                    <group position={[0, 0.02, 0]} rotation={[0.83, -0.29, -2.62]}>
                                      <group position={[0, 0.01, 0]} rotation={[0.15, 0.18, 0.06]}>
                                        <group position={[0, 0.02, 0]} rotation={[0.4, 0.29, 0.38]} />
                                      </group>
                                    </group>
                                  </group>
                                </group>
                              </group>
                            </group>
                            <group position={[-0.08, 0.12, 0.1]} rotation={[-0.95, -0.91, -1.96]}>
                              <group position={[0, 0.02, 0]} rotation={[-0.48, -0.74, -0.04]}>
                                <group position={[0, 0.01, 0]} rotation={[-0.09, -0.4, 0.6]} />
                              </group>
                            </group>
                            <group position={[-0.08, 0.11, 0.1]} rotation={[-0.85, -0.96, -2]}>
                              <group position={[0, 0.02, 0]} rotation={[-0.28, -0.88, 0.18]}>
                                <group position={[0, 0.02, 0]} rotation={[-0.32, -0.42, 0.59]}>
                                  <group position={[0, 0.01, 0]} rotation={[-0.24, -0.56, 0.03]}>
                                    <group position={[0, 0.02, 0]} rotation={[0.83, 0.29, 2.62]}>
                                      <group position={[0, 0.01, 0]} rotation={[0.15, -0.18, -0.06]}>
                                        <group position={[0, 0.02, 0]} rotation={[0.4, -0.29, -0.38]} />
                                      </group>
                                    </group>
                                  </group>
                                </group>
                              </group>
                            </group>
                            <group position={[0.02, 0.19, 0.11]} rotation={[-2.26, 1.49, -1.26]}>
                              <group position={[-0.01, -0.01, 0.03]} rotation={[0.09, -0.26, -0.09]}>
                                <group position={[-0.02, 0, 0.03]} rotation={[-0.01, -0.57, 0]}>
                                  <group position={[-0.02, 0, 0.04]} rotation={[0.52, -0.61, 0.44]}>
                                    <group position={[0, 0.08, 0]} rotation={[0.03, -0.26, 0.26]}>
                                      <group position={[0, 0.08, 0]} rotation={[-0.21, -0.66, 0.73]}>
                                        <group position={[0, 0.09, 0]} rotation={[-2, -0.14, 1.31]}>
                                          <group position={[0, 0.06, 0]} rotation={[-1.53, -0.1, -0.76]}>
                                            <group position={[0, 0.05, 0]} rotation={[0.56, 0.59, 0.44]}>
                                              <group position={[0, 0.07, 0]} rotation={[1.17, 0.49, 0.01]}>
                                                <group position={[0, 0.04, 0]} rotation={[-2.07, 0.64, 1.94]}>
                                                  <group position={[0, 0.03, 0]} rotation={[-0.46, 0.85, -0.25]} />
                                                </group>
                                              </group>
                                            </group>
                                          </group>
                                        </group>
                                      </group>
                                    </group>
                                  </group>
                                </group>
                              </group>
                            </group>
                            <group position={[-0.02, 0.19, 0.11]} rotation={[-2.26, -1.49, 1.26]}>
                              <group position={[0.01, -0.01, 0.03]} rotation={[0.09, 0.26, 0.09]}>
                                <group position={[0.02, 0, 0.03]} rotation={[-0.01, 0.57, 0]}>
                                  <group position={[0.02, 0, 0.04]} rotation={[0.52, 0.61, -0.44]}>
                                    <group position={[0, 0.08, 0]} rotation={[0.03, 0.26, -0.26]}>
                                      <group position={[0, 0.08, 0]} rotation={[-0.21, 0.66, -0.73]}>
                                        <group position={[0, 0.09, 0]} rotation={[-2, 0.14, -1.31]}>
                                          <group position={[0, 0.06, 0]} rotation={[-1.53, 0.1, 0.76]}>
                                            <group position={[0, 0.05, 0]} rotation={[0.56, -0.59, -0.44]}>
                                              <group position={[0, 0.07, 0]} rotation={[1.17, -0.49, -0.01]}>
                                                <group position={[0, 0.04, 0]} rotation={[-2.07, -0.64, -1.94]}>
                                                  <group position={[0, 0.03, 0]} rotation={[-0.46, -0.85, 0.25]} />
                                                </group>
                                              </group>
                                            </group>
                                          </group>
                                        </group>
                                      </group>
                                    </group>
                                  </group>
                                </group>
                              </group>
                            </group>
                            <group position={[0.08, 0.11, 0.07]} rotation={[3.05, -1.02, 0.94]}>
                              <group position={[0, 0.07, 0]} rotation={[2.88, -0.65, 1.44]}>
                                <group position={[0, 0.05, 0]} rotation={[2.7, 0.67, 1.25]} />
                              </group>
                            </group>
                            <group position={[-0.08, 0.11, 0.07]} rotation={[3.05, 1.02, -0.94]}>
                              <group position={[0, 0.07, 0]} rotation={[2.88, 0.65, -1.44]}>
                                <group position={[0, 0.05, 0]} rotation={[2.7, -0.67, -1.25]} />
                              </group>
                            </group>
                            <group position={[0, 0.01, 0.11]} rotation={[-1.35, 0, 0]}>
                              <group position={[0, 0.03, 0]} rotation={[-0.37, 0, 0]} />
                            </group>
                          </group>
                        </group>
                      </group>
                    </group>
                    <group position={[0.02, 0.08, 0.07]} rotation={[-1.74, 0.09, -1.22]}>
                      <group position={[0, 0.19, -0.03]} rotation={[2.58, 1.39, 2.36]}>
                        <group position={[0, 0.31, 0]} rotation={[0.56, 0.31, -0.17]}>
                          <group position={[0, 0.28, 0]} rotation={[-0.35, -0.03, -0.08]}>
                            <group position={[-0.01, 0.04, 0.02]} rotation={[-2.86, 1.41, 3.02]}>
                              <group position={[0, 0.07, 0]} rotation={[0.3, -0.08, 0.13]}>
                                <group position={[0, 0.05, 0]} rotation={[0.28, -0.05, 0.13]} />
                              </group>
                              <group position={[-0.02, -0.01, 0]} rotation={[-1.98, 0.96, 2.32]}>
                                <group position={[0, 0.05, 0]} rotation={[0.18, -0.3, 0.44]} />
                              </group>
                            </group>
                            <group position={[-0.01, 0.04, 0]} rotation={[-2.79, 1.51, 2.88]}>
                              <group position={[0, 0.08, 0]} rotation={[0.35, -0.01, 0.17]}>
                                <group position={[0, 0.05, 0]} rotation={[0.34, -0.14, 0.07]} />
                              </group>
                            </group>
                            <group position={[0, 0.04, -0.02]} rotation={[-0.08, 1.46, 0.03]}>
                              <group position={[0, 0.07, 0]} rotation={[0.38, 0.02, 0.12]}>
                                <group position={[0, 0.05, 0]} rotation={[0.38, -0.07, 0.02]} />
                              </group>
                            </group>
                            <group position={[0, 0.04, -0.03]} rotation={[0.13, 1.35, -0.33]}>
                              <group position={[0, 0.07, 0]} rotation={[0.38, -0.05, 0.25]}>
                                <group position={[0, 0.05, 0]} rotation={[0.2, -0.05, 0]} />
                              </group>
                            </group>
                          </group>
                        </group>
                      </group>
                    </group>
                    <group position={[-0.02, 0.08, 0.07]} rotation={[-1.74, -0.09, 1.22]}>
                      <group position={[0, 0.19, -0.03]} rotation={[2.58, -1.39, -2.36]}>
                        <group position={[0, 0.31, 0]} rotation={[0.56, -0.31, 0.17]}>
                          <group position={[0, 0.28, 0]} rotation={[-0.35, 0.03, 0.08]}>
                            <group position={[0.01, 0.04, 0.02]} rotation={[-2.86, -1.41, -3.02]}>
                              <group position={[0, 0.07, 0]} rotation={[0.3, 0.08, -0.13]}>
                                <group position={[0, 0.05, 0]} rotation={[0.28, 0.05, -0.13]} />
                              </group>
                              <group position={[0.02, -0.01, 0]} rotation={[-1.98, -0.96, -2.32]}>
                                <group position={[0, 0.05, 0]} rotation={[0.18, 0.3, -0.44]} />
                              </group>
                            </group>
                            <group position={[0.01, 0.04, 0]} rotation={[-2.79, -1.51, -2.88]}>
                              <group position={[0, 0.08, 0]} rotation={[0.35, 0.01, -0.17]}>
                                <group position={[0, 0.05, 0]} rotation={[0.34, 0.14, -0.07]} />
                              </group>
                            </group>
                            <group position={[0, 0.04, -0.02]} rotation={[-0.08, -1.46, -0.03]}>
                              <group position={[0, 0.07, 0]} rotation={[0.38, -0.02, -0.12]}>
                                <group position={[0, 0.05, 0]} rotation={[0.38, 0.07, -0.02]} />
                              </group>
                            </group>
                            <group position={[0, 0.04, -0.03]} rotation={[0.13, -1.35, 0.33]}>
                              <group position={[0, 0.07, 0]} rotation={[0.38, 0.05, -0.25]}>
                                <group position={[0, 0.05, 0]} rotation={[0.2, 0.05, 0]} />
                              </group>
                            </group>
                          </group>
                        </group>
                      </group>
                    </group>
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
        <group position={[0.1, 0.04, 0.09]} rotation={[2.92, 0.01, 0.04]}>
          <group position={[0, 0.49, 0]} rotation={[0.07, -0.02, -0.05]}>
            <group position={[0, 0.46, 0]} rotation={[-1.12, 0, 0.01]} />
          </group>
        </group>
        <group position={[-0.11, 0.04, 0.09]} rotation={[2.92, 0, -0.04]}>
          <group position={[0, 0.49, 0]} rotation={[0.07, 0.02, 0.05]}>
            <group position={[0, 0.46, 0]} rotation={[-1.12, 0, -0.01]} />
          </group>
        </group>
      </group>
      <mesh
        geometry={nodes.Medula.geometry}
        material={materials.Medula}
        position={[0.01, 0.74, 0]}
        rotation={[Math.PI, 1.51, -2.13]}
        scale={[0.05, 0.05, 0.05]}
      />
      <mesh
        geometry={nodes.BezierCurve.geometry}
        material={materials['Material.001']}
        position={[-0.03, 0.69, 0.02]}
        rotation={[0, 0.96, 1.72]}
        scale={0.08}
      />
      <mesh
        geometry={nodes.BezierCurve001.geometry}
        material={materials['Material.002']}
        position={[-0.02, 0.67, 0.01]}
        rotation={[-0.18, 0.95, 1.94]}
        scale={0.08}
      />
      <mesh
        geometry={nodes.BezierCurve002.geometry}
        material={materials['Material.003']}
        position={[-0.02, 0.67, 0.01]}
        rotation={[-0.18, 0.95, 1.94]}
        scale={0.08}
      />
      <mesh
        geometry={nodes.BezierCurve003.geometry}
        material={materials['Material.004']}
        position={[-0.02, 0.47, -0.04]}
        rotation={[-0.18, 0.95, 1.94]}
        scale={0.08}
      />
      <mesh
        geometry={nodes.BezierCurve004.geometry}
        material={materials['Material.005']}
        position={[-0.02, 0.44, -0.04]}
        rotation={[-0.18, 0.95, 1.94]}
        scale={0.08}
      />
      <mesh
        geometry={nodes.BezierCurve005.geometry}
        material={materials['Material.006']}
        position={[-0.02, 0.42, -0.04]}
        rotation={[-0.18, 0.95, 1.94]}
        scale={0.08}
      />
      <mesh
        geometry={nodes.BezierCurve006.geometry}
        material={materials['Material.007']}
        position={[-0.02, 0.39, -0.04]}
        rotation={[-0.18, 0.95, 1.94]}
        scale={0.08}
      />
      <mesh
        geometry={nodes.BezierCurve007.geometry}
        material={materials['Material.008']}
        position={[-0.02, 0.36, -0.03]}
        rotation={[-0.18, 0.95, 1.94]}
        scale={0.08}
      />
      <mesh
        geometry={nodes.BezierCurve008.geometry}
        material={materials['Material.009']}
        position={[-0.02, 0.33, -0.02]}
        rotation={[-0.18, 0.95, 1.94]}
        scale={0.08}
      />
      <mesh
        geometry={nodes.BezierCurve009.geometry}
        material={materials['Material.010']}
        position={[-0.02, 0.3, -0.02]}
        rotation={[-0.18, 0.95, 1.94]}
        scale={0.08}
      />
      <mesh
        geometry={nodes.BezierCurve010.geometry}
        material={materials['Material.011']}
        position={[-0.02, 0.27, -0.01]}
        rotation={[-0.18, 0.95, 1.94]}
        scale={0.08}
      />
      <mesh
        geometry={nodes.BezierCurve011.geometry}
        material={materials['Material.012']}
        position={[-0.02, 0.23, 0]}
        rotation={[-0.18, 0.95, 1.94]}
        scale={0.08}
      />
      <mesh
        geometry={nodes.BezierCurve012.geometry}
        material={materials['Material.013']}
        position={[-0.02, 0.2, 0]}
        rotation={[-0.18, 0.95, 1.94]}
        scale={0.08}
      />
      <mesh
        geometry={nodes.BezierCurve013.geometry}
        material={materials['Material.014']}
        position={[-0.02, 0.16, 0.02]}
        rotation={[-0.33, 1.24, 2.1]}
        scale={0.08}
      />
      <mesh
        geometry={nodes.BezierCurve014.geometry}
        material={materials['Material.015']}
        position={[-0.02, 0.13, 0.01]}
        rotation={[-0.18, 0.95, 1.94]}
        scale={0.08}
      />
      <mesh
        geometry={nodes.BezierCurve015.geometry}
        material={materials['Material.016']}
        position={[-0.02, 0.1, 0.01]}
        rotation={[-0.18, 0.95, 1.94]}
        scale={0.08}
      />
    </group>
  )
}

useGLTF.preload('/skeleton-test.glb')
